services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: lavalink
    volumes:
      - ./lavalink-config:/opt/Lavalink/config
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - YOUTUBE_REFRESH_TOKEN=${YOUTUBE_REFRESH_TOKEN}
    restart: unless-stopped
    networks:
      - bot-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LAVALINK_HOST=${LAVALINK_HOST}
      - LAVALINK_PORT=${LAVALINK_PORT}
    restart: unless-stopped
    depends_on:
      - lavalink
    networks:
      - bot-network

networks:
  bot-network:
