services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: lavalink
    hostname: lavalink
    volumes:
      - ./lavalink-config:/opt/Lavalink/config
    environment:
      - _JAVA_OPTIONS=-Xmx8G -Xms4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      - YOUTUBE_REFRESH_TOKEN=${YOUTUBE_REFRESH_TOKEN}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - GOOGLE_SECRET_ID=${GOOGLE_SECRET_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NO_PROXY="maven.topi.wtf,maven.org,*.github.com"
      - HTTP_PROXY=http://proxy:3128
      - HTTPS_PROXY=http://proxy:3128
    restart: unless-stopped
    depends_on:
      proxy:
        condition: service_started
    networks:
      - undefined-bot
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider --header='Authorization: youshallnotpass' http://localhost:2333/version || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  proxy:
    image: sameersbn/squid:3.5.27-2
    container_name: lavalink-proxy
    restart: unless-stopped
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
    networks:
      - undefined-bot

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: undefined-bot
    hostname: undefined-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - COMMAND_PREFIX=${COMMAND_PREFIX:-u$}
      - TIMEOUT_MINUTES=${TIMEOUT_MINUTES:-2}
      - YOUTUBE_REFRESH_TOKEN=${YOUTUBE_REFRESH_TOKEN}
      - LAVALINK_HOST=lavalink
      - LAVALINK_PORT=2333
      - LAVALINK_PASSWORD=youshallnotpass
      - ADDRESS=${ADDRESS}
      - GOOGLE_SECRET_ID=${GOOGLE_SECRET_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    restart: unless-stopped
    depends_on:
      lavalink:
        condition: service_healthy
    networks:
      - undefined-bot

networks:
  undefined-bot:
    driver: bridge
