acl localnet src all
http_access allow localnet
http_port 3128 intercept  # transparent
https_port 3129 intercept ssl-bump cert=/etc/squid/ssl.crt key=/etc/squid/ssl.key generate-host-certificates=on dynamic_cert_mem_cache_size=4MB
